import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Error404() {
  return (
    <>
      <Head>
        <title>Skyrats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <meta property="og:title" content="Equipe de drones"/>
        <meta property="og:site_name" content="Skyrats"/>
        <meta property="og:url" content="skyrats.com.br"/>
        <meta property="og:description" content="Nós somos a equipe de drones autônomos da POLI-USP, fundada em 2017, vencedora de diversos campeonatos nacionais e internacionais, venha conferir nosso website!"/>
        <meta property="og:type" content="website"/>
        <meta property="og:image" content="/banner.png"/>
      </Head>
      <main>
        ERRO 404
      </main>
    </>
  )
}
